FILE_PATH = "spam_ham.csv"
CSV_SEPARATOR = ";"
CSV_ENCODING = "latin-1"

LABEL_COL = "Label"
TEXT_COL = "SMS_TEXT"

SPAM_LABEL = "spam"
HAM_LABEL = "ham"

RANDOM_SAMPLE_SIZE = 5
TOP_WORDS_COUNT = 20

WORDCLOUD_WIDTH = 800
WORDCLOUD_HEIGHT = 400
WORDCLOUD_BACKGROUND = "white"

STOPWORDS_LANGUAGE = "english"
